[package]
name = "rade"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
git2="0.19.0"
reqwest = { version = "0.11", features = ["blocking"] }
